TASK_NAMES=(
  "PnPMicrowaveToCounter"
  "TurnSinkSpout"
  "TurnOnStove"
  "TurnOnSinkFaucet"
  "TurnOnMicrowave"
  "TurnOffStove"
  "TurnOffSinkFaucet"
  "TurnOffMicrowave"
  "PnPStoveToCounter"
  "PnPSinkToCounter"
  "PnPCounterToStove"
  "PnPCounterToSink"
  "PnPCounterToMicrowave"
  "PnPCounterToCab"
  "PnPCabToCounter"
  "OpenSingleDoor"
  "OpenDrawer"
  "OpenDoubleDoor"
  "CoffeeSetupMug"
  "CoffeeServeMug"
  "CoffeePressButton"
  "CloseSingleDoor"
  "CloseDrawer"
  "CloseDoubleDoor"
)

for TASK_NAME in ${TASK_NAMES[@]}; do
  eval "hf download GR00T-Dateset/single_panda_gripper-${TASK_NAME} --repo-type dataset --local-dir ~/data/robocasa_full/single_panda_gripper.${TASK_NAME}"
done